# Generated by Django 4.1 on 2024-04-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=255)),
                ("pallet", models.CharField(max_length=255)),
                ("peso", models.CharField(max_length=255)),
                ("salida", models.CharField(max_length=255)),
                ("destino", models.CharField(max_length=255)),
            ],
        ),
    ]
