# Generated by Django 4.1 on 2024-04-30 21:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datosTote", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tote",
            name="identificador",
        ),
        migrations.RemoveField(
            model_name="tote",
            name="peso",
        ),
    ]
